import type { PrototypeManifest } from '@wts/prototype-kit'
import { flow } from './flow.generated'

/**
 * Pure-data description of this prototype for the gallery (index card, flow
 * canvas layout, Figma export). NO React imports — the gallery imports this
 * module directly.
 *
 * `flow` is AUTO-GENERATED by `scripts/gen-flow.ts` from the prototype's own
 * `isValidContext` + control rules, so the canvas always matches what the app
 * can actually render. Regenerate with `pnpm gen:flow` (runs on build).
 */
const manifest: PrototypeManifest = {
  id: 'vat-group-case',
  title: 'VAT Group Case',
  description:
    'Dedicated home for the VAT Group Case workflow: Case Management (Parent/Child VAT Group Cases), Single/Group Case creation drawers, and the VAT Scheduler — cloned from wts-process-extension for feature parity ahead of splitting VAT Group Case ownership out of it.',
  basePath: '/prototypes/vat-group-case/',
  defaultHash: 'vat/creator/case/inPreparation',
  // Same design file as wts-process-extension — this prototype is a clone of it, same components.
  figmaFileKey: 's7egAC96sEnmBjGo4ngKvz',
  flow,
}

export default manifest
