/**
 * Generates src/flow.generated.ts — the full set of navigable screens and the
 * flow between them — from the prototype's OWN validity logic, so the gallery
 * canvas always reflects exactly what the app can render.
 *
 * Run with vite-node (resolves the `@/` alias): `pnpm gen:flow`.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import type { FlowGraph, ScreenDef, FlowEdgeDef } from '@wts/prototype-kit'
import type { HeaderType, Phase, Process, Role } from '@/types'
import { isValidContext, platformForRole, headerTypesForRole, ALL_ROLES } from '@/lib/resolveHeader'
import { workflowPhasesForControls, PHASE_LABELS } from '@/config/phases'
import { isHeaderTypeAllowedInControls, isPhaseDisabledInControls } from '@/lib/controlHeaderTypes'

const PROCESSES: Process[] = ['cit', 'hr', 'vat']

const PROCESS_LABEL: Record<Process, string> = { cit: 'CIT', hr: 'HR', vat: 'VAT' }
const ROLE_LABEL: Record<Role, string> = {
  creator: 'Creator',
  reviewer: 'Reviewer',
  partner: 'Partner',
  client: 'Client',
}
const VIEW_LABEL: Record<HeaderType, string> = {
  caseWrapper: 'Engagement',
  case: 'Case',
  requirementList: 'Requirements',
  requirementBucket: 'Requirement bucket',
}

const screens: ScreenDef[] = []
const edges: FlowEdgeDef[] = []
const seen = new Set<string>()

const screenId = (p: Process, r: Role, h: HeaderType, ph: Phase) => `${p}-${r}-${h}-${ph}`

for (const process of PROCESSES) {
  const phases = workflowPhasesForControls(process)
  for (const role of ALL_ROLES) {
    const platform = platformForRole(role)
    for (const phase of phases) {
      if (isPhaseDisabledInControls(phase, role)) continue
      const col = phases.indexOf(phase)
      for (const headerType of headerTypesForRole(process, role)) {
        if (!isHeaderTypeAllowedInControls(headerType, process, role, phase)) continue
        if (!isValidContext({ process, platform, role, headerType, phase })) continue

        const id = screenId(process, role, headerType, phase)
        if (seen.has(id)) continue
        seen.add(id)

        const viewSuffix = headerType === 'case' ? '' : ` · ${VIEW_LABEL[headerType]}`
        screens.push({
          id,
          label: `${PHASE_LABELS[phase]}${viewSuffix}`,
          hash: `${process}/${role}/${headerType}/${phase}`,
          group: `${process}:${role}`,
          lane: `${PROCESS_LABEL[process]} · ${ROLE_LABEL[role]}`,
          col,
          meta: {
            process: PROCESS_LABEL[process],
            role: ROLE_LABEL[role],
            phase: PHASE_LABELS[phase],
            view: VIEW_LABEL[headerType],
          },
        })
      }
    }
  }
}

// Edges: (1) the case/engagement workflow spine per (process, role) connects
// consecutive phases; (2) at each phase, the case branches to its requirement view.
for (const process of PROCESSES) {
  const order = workflowPhasesForControls(process)
  const phaseIndex = (ph: Phase) => order.indexOf(ph)
  for (const role of ALL_ROLES) {
    for (const spine of ['caseWrapper', 'case'] as HeaderType[]) {
      const chain = screens
        .filter((s) => s.group === `${process}:${role}` && s.id.includes(`-${spine}-`))
        .sort((a, b) => phaseIndex(a.hash.split('/')[3] as Phase) - phaseIndex(b.hash.split('/')[3] as Phase))
      for (let i = 0; i < chain.length - 1; i++) {
        edges.push({
          from: chain[i].id,
          to: chain[i + 1].id,
          label: chain[i + 1].meta?.phase,
        })
      }
    }

    // case -> requirement view at the same phase
    for (const reqType of ['requirementList', 'requirementBucket'] as HeaderType[]) {
      for (const reqScreen of screens.filter(
        (s) => s.group === `${process}:${role}` && s.id.includes(`-${reqType}-`),
      )) {
        const phase = reqScreen.hash.split('/')[3] as Phase
        const caseId = screenId(process, role, 'case', phase)
        if (seen.has(caseId)) edges.push({ from: caseId, to: reqScreen.id, label: 'Requirements' })
      }
    }
  }
}

const flow: FlowGraph = { screens, edges }

const out = `// AUTO-GENERATED by scripts/gen-flow.ts — do not edit by hand. Run \`pnpm gen:flow\`.
import type { FlowGraph } from '@wts/prototype-kit'

export const flow: FlowGraph = ${JSON.stringify(flow, null, 2)}
`

const target = resolve(dirname(fileURLToPath(import.meta.url)), '../src/flow.generated.ts')
writeFileSync(target, out)
console.log(`[gen-flow] wrote ${screens.length} screens, ${edges.length} edges -> src/flow.generated.ts`)
