import type { PrototypeManifest } from '@wts/prototype-kit'
import { flow } from './flow.generated'

/**
 * Pure-data description of this prototype for the gallery (index card, flow
 * canvas layout, Figma export). NO React imports — the gallery imports this
 * module directly.
 *
 * `flow` is AUTO-GENERATED by `scripts/gen-flow.ts` from the prototype's own
 * `isValidContext` + control rules, so the canvas always matches what the app
 * can actually render. Regenerate with `pnpm gen:flow` (runs on build).
 */
const manifest: PrototypeManifest = {
  id: 'wts-process-extension',
  title: 'Process Extension — CIT Assessment & Closure',
  description:
    'Corporate income-tax case workflow across Creator, Reviewer, Partner and Client roles: preparation, maker/checker review, client approval, submission and assessment closure.',
  basePath: '/prototypes/wts-process-extension/',
  defaultHash: 'cit/creator/case/inPreparation',
  // WTS designs file (from the original figma-upload.sh). Enables the Designs tab.
  figmaFileKey: 's7egAC96sEnmBjGo4ngKvz',
  flow,
}

export default manifest
